---
title: "Final_Project"
author: "Hao Xu"
format: html
---
```{r}
library(here)
library(ggplot2)
library(dplyr)
library(tidyr)
library(knitr)
here::i_am("Final_Project.Rproj")
```

The data of Pisa are available only in SAV format, in order to use the data, we need install some libraries so that we can treat with SAV files. The data from 2000-2012 are got
through SPSS.
```{r}
library(haven)
library(tidyverse)
```

```{r}
pisa2022 <- read_sav(here("Data", "Pisa_Raw", "Student2022.SAV"))
```

```{r}
pisa2022_clean <- pisa2022 %>%
  mutate(year = 2022) %>%
  
  mutate(
    computer_n = as.numeric(ST254Q02JA) + as.numeric(ST254Q03JA),
    gender = as_factor(ST004D01T)
  ) %>%
  select(
    year,                       
    country = CNT,              
    school_id = CNTSCHID,       
    student_id = CNTSTUID,    
    
    mother_educ = ST005Q01JA,   
    father_educ = ST007Q01JA,   
    gender,                     
    
    room = ST250Q01JA,          
    computer = ST250Q02JA,      
    internet = ST250Q05JA,      
    
    car = ST251Q01JA,           
    television = ST254Q01JA,    
    computer_n,               
    book = ST255Q01JA,          
    
    math = PV1MATH,             
    read = PV1READ,             
    science = PV1SCIE,          
    stu_wgt = W_FSTUWT,         
    
    wealth = HOMEPOS,            
    escs = ESCS               
  ) %>%
  

  zap_labels()

output_dir <- here("Data", "Pisa_clean")

write_rds(pisa2022_clean, file.path(output_dir, "pisa2022_clean.rds"))
```



```{r}
pisa2018 <- read_sav(here("Data", "Pisa_Raw", "Student2018.sav"))
```

```{r}
pisa2018_clean <- pisa2018 %>%
  
  mutate(year = 2018) %>%
  mutate(
    computer_n = as.numeric(ST012Q06NA),
    
    gender = as_factor(ST004D01T)
  ) %>%

  select(
    year,
    country = CNT,
    school_id = CNTSCHID,
    student_id = CNTSTUID,
    
    mother_educ = MISCED,       
    father_educ = FISCED,       
    gender,
    
    room = ST011Q02TA,          
    computer = ST011Q04TA,      
    internet = ST011Q06TA,      
    desk = ST011Q01TA,  
    
    car = ST012Q02TA,           
    television = ST012Q01TA,    
    computer_n,                 
    
    book = ST013Q01TA,          
    
    math = PV1MATH,
    read = PV1READ,
    science = PV1SCIE,
    stu_wgt = W_FSTUWT,
    
    wealth = HOMEPOS,           
    escs = ESCS
  ) %>%
  
  zap_labels()

output_dir <- here("Data", "Pisa_clean")

write_rds(pisa2018_clean, file.path(output_dir, "pisa2018_clean.rds"))
```

```{r}
pisa2015 <- read_sav(here("Data", "Pisa_Raw", "Student2015.sav"))
```

```{r}
pisa2015_clean <- pisa2015 %>%
  
  mutate(year = 2015) %>%
  mutate(
    computer_n = as.numeric(ST012Q06NA),,
    
    gender = as_factor(ST004D01T)
  ) %>%

  select(
    year,
    country = CNT,
    school_id = CNTSCHID,
    student_id = CNTSTUID,
    
    mother_educ = MISCED,       
    father_educ = FISCED,       
    gender,

    room = ST011Q02TA,          
    computer = ST011Q04TA,      
    internet = ST011Q06TA,      
    desk = ST011Q01TA,   
    
    car = ST012Q02TA,           
    television = ST012Q01TA,    
    computer_n,                 
    
    book = ST013Q01TA,          
    
    math = PV1MATH,
    read = PV1READ,
    science = PV1SCIE,
    stu_wgt = W_FSTUWT,
    
    wealth = HOMEPOS,           
    escs = ESCS
  ) %>%
  
  zap_labels()

output_dir <- here("Data", "Pisa_clean")

write_rds(pisa2015_clean, file.path(output_dir, "pisa2015_clean.rds"))
```

```{r}
pisa2012 <- read_sav(here("Data", "Pisa_Raw", "Student2012.sav"))
```

```{r}
pisa2012_clean <- pisa2012 %>%
  
  mutate(year = 2012) %>%
  
  mutate(
    computer_n = as.numeric(ST27Q03),
    
    gender = as_factor(ST04Q01)
  ) %>%

  select(
    year,
    country = CNT,              
    school_id = SCHOOLID,      
    student_id = StIDStd,       
    
    mother_educ = ST13Q01,      
    father_educ = ST17Q01,      
    
    gender,
    
    room = ST26Q02,             
    computer = ST26Q04,          
    internet = ST26Q06,         
    desk = ST26Q01,             
    
    
    car = ST27Q04,              
    television = ST27Q02,       
    computer_n,                 
    
    book = ST28Q01,             
    
    math = PV1MATH,
    read = PV1READ,
    science = PV1SCIE,
    stu_wgt = W_FSTUWT,
  
    wealth = HOMEPOS,            
    escs = ESCS
  ) %>%
  
  zap_labels()

output_dir <- here("Data", "Pisa_clean")


write_rds(pisa2012_clean, file.path(output_dir, "pisa2012_clean.rds"))
```

```{r}
pisa2009 <- read_sav(here("Data", "Pisa_Raw", "Student2009.sav"))
```
```{r}

pisa2009_clean <- pisa2009 %>%
  
  mutate(year = 2009) %>%
  
  mutate(
    computer_n = as.numeric(ST21Q03),
    gender = as_factor(ST04Q01)
  ) %>%

  select(
    year,
    country = CNT,
    school_id = SCHOOLID,
    student_id = StIDStd,
    
    mother_educ = ST10Q01,      
    father_educ = ST14Q01,      
    
    gender,
    
    room = ST20Q02,             
    computer = ST20Q04,         
    internet = ST20Q06,         
    desk = ST20Q01,             
    
    
    car = ST21Q02,              
    television = ST21Q01,       
    computer_n,                 
    
    book = ST22Q01,             
    
    math = PV1MATH,
    read = PV1READ,
    science = PV1SCIE,
    stu_wgt = W_FSTUWT,
    
    wealth = HOMEPOS,            
    escs = ESCS
  ) %>%
  
  zap_labels()

output_dir <- here("Data", "Pisa_clean")

write_rds(pisa2009_clean, file.path(output_dir, "pisa2009_clean.rds"))
```

```{r}
pisa2006 <- read_sav(here("Data", "Pisa_Raw", "Student2006.sav"))
```

```{r}
pisa2006_clean <- pisa2006 %>%
  
  mutate(year = 2006) %>%
  
  mutate(
    computer_n = as.numeric(ST14Q03),
    
        gender = as_factor(ST04Q01)
  ) %>%

  select(
    year,
    country = CNT,
    school_id = SCHOOLID,
    student_id = STIDSTD,     
    
    mother_educ = ST06Q01,
    father_educ = ST09Q01,
    
    gender,
    
    room = ST13Q02,
    computer = ST13Q04,
    internet = ST13Q06,
    desk = ST13Q01,
    
    
    car = ST14Q04,
    television = ST14Q02,
    computer_n,               
    
    book = ST15Q01,
    
    math = PV1MATH,
    read = PV1READ,
    science = PV1SCIE,
    stu_wgt = W_FSTUWT,
    
    wealth = HOMEPOS,           
    escs = ESCS
  ) %>%
  
  zap_labels()

output_dir <- here("Data", "Pisa_clean")

write_rds(pisa2006_clean, file.path(output_dir, "pisa2006_clean.rds"))
```



```{r}
pisa2003 <- read_sav(here("Data", "Pisa_Raw", "Student2003.sav"))
```

```{r}
pisa2003_clean <- pisa2003 %>%
  
  mutate(year = 2003) %>%
  
  mutate(
    computer_n = as.numeric(ST17Q04),
    
    gender = as_factor(ST03Q01),
    car = NA_real_,
    television = NA_real_
  ) %>%

  select(
    year,
    country = CNT,
    school_id = SCHOOLID,
    student_id = STIDSTD,
    
    mother_educ = ST11R01,
    father_educ = ST13R01,
    
    gender,
    
    room = ST17Q02,
    computer = ST17Q04,
    internet = ST17Q06,
    desk = ST17Q01,
    
    
    car ,           
    television,     
    computer_n,              
    
    book = ST19Q01,
    
    math = PV1MATH,
    read = PV1READ,
    science = PV1SCIE,
    stu_wgt = W_FSTUWT,
    
    wealth = HOMEPOS,       
    escs = ESCS
  ) %>%
  
  zap_labels()

output_dir <- here("Data", "Pisa_clean")

write_rds(pisa2003_clean, file.path(output_dir, "pisa2003_clean.rds"))
```


